from pathlib import Path
from named_proof import Proof
p=Proof();a=p.add
a('sg',r'\SemigroupAlg{A}{\star}',r'\rA')
a('e',r'e\in A',r'\rA')
a('neutral',r'\forall x\in A\;(ex=x\land xe=x)',r'\rA')
a('subset',r'U(A,e)\subseteq A',r'\FormulaRefAuto{SemigroupUnitsAtIdentityDef}[def]{@sg,@e,@neutral}')
a('idem',r'ee=e',r'\rAEa{\rRE{\rUE{@neutral},@e}}')
a('e_inverse',r'\exists v\in A\;(ev=e\land ve=e)',r'\rEIStar{@e,\rAI{@idem,@idem}}')
a('e_unit',r'e\in U(A,e)',r'\FormulaRefAuto{SemigroupUnitsAtIdentityDef}[def]{@sg,@e,@neutral,@e_inverse}')
a('nonempty',r'U(A,e)\neq\varnothing',r'\FormulaRefAuto{a\in A\vdash A\neq\varnothing}[thm]{@e_unit}')
a('u',r'u\in U(A,e)',r'\rA')
a('v',r'v\in U(A,e)',r'\rA')
a('u_a',r'u\in A',r'\FormulaRefAuto{A\subseteq B,\,x\in A\vdash x\in B}[thm]{@subset,@u}')
a('v_a',r'v\in A',r'\FormulaRefAuto{A\subseteq B,\,x\in A\vdash x\in B}[thm]{@subset,@v}')
a('u_exists',r'\exists u^{\prime}\in A\;(uu^{\prime}=e\land u^{\prime}u=e)',r'\FormulaRefAuto{SemigroupUnitsAtIdentityDef}[def]{@sg,@e,@neutral,@u}')
a('uw',r'u^{\prime}\in A\land uu^{\prime}=e\land u^{\prime}u=e',r'\rA')
a('up',r'u^{\prime}\in A',r'\rAEa{@uw}')
a('uu',r'uu^{\prime}=e',r'\rAEa{\rAEb{@uw}}')
a('upu',r'u^{\prime}u=e',r'\rAEb{\rAEb{@uw}}')
a('v_exists',r'\exists v^{\prime}\in A\;(vv^{\prime}=e\land v^{\prime}v=e)',r'\FormulaRefAuto{SemigroupUnitsAtIdentityDef}[def]{@sg,@e,@neutral,@v}')
a('vw',r'v^{\prime}\in A\land vv^{\prime}=e\land v^{\prime}v=e',r'\rA')
a('vp',r'v^{\prime}\in A',r'\rAEa{@vw}')
a('vv',r'vv^{\prime}=e',r'\rAEa{\rAEb{@vw}}')
a('vpv',r'v^{\prime}v=e',r'\rAEb{\rAEb{@vw}}')
a('uv',r'uv\in A',r'\FormulaRefAuto{SemigroupClosureAxiom}[ax]{@sg,@u_a,@v_a}')
a('inv',r'v^{\prime}u^{\prime}\in A',r'\FormulaRefAuto{SemigroupClosureAxiom}[ax]{@sg,@vp,@up}')
a('left_assoc',r'(uv)(v^{\prime}u^{\prime})=u(v(v^{\prime}u^{\prime}))',r'\FormulaRefAuto{SemigroupAssociativityAxiom}[ax]{@sg,@u_a,@v_a,@inv}')
a('inner_left_assoc',r'(vv^{\prime})u^{\prime}=v(v^{\prime}u^{\prime})',r'\FormulaRefAuto{SemigroupAssociativityAxiom}[ax]{@sg,@v_a,@vp,@up}')
a('inner_left_sym',r'v(v^{\prime}u^{\prime})=(vv^{\prime})u^{\prime}',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@inner_left_assoc}')
a('eup',r'eu^{\prime}=u^{\prime}',r'\rAEa{\rRE{\rUE{@neutral},@up}}')
a('inner_left',r'v(v^{\prime}u^{\prime})=u^{\prime}',r'\rIE{@vv,@eup,@inner_left_sym}')
a('left',r'(uv)(v^{\prime}u^{\prime})=e',r'\rIE{@inner_left,@uu,@left_assoc}')
a('right_assoc',r'(v^{\prime}u^{\prime})(uv)=v^{\prime}(u^{\prime}(uv))',r'\FormulaRefAuto{SemigroupAssociativityAxiom}[ax]{@sg,@vp,@up,@uv}')
a('inner_right_assoc',r'(u^{\prime}u)v=u^{\prime}(uv)',r'\FormulaRefAuto{SemigroupAssociativityAxiom}[ax]{@sg,@up,@u_a,@v_a}')
a('inner_right_sym',r'u^{\prime}(uv)=(u^{\prime}u)v',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@inner_right_assoc}')
a('ev',r'ev=v',r'\rAEa{\rRE{\rUE{@neutral},@v_a}}')
a('inner_right',r'u^{\prime}(uv)=v',r'\rIE{@upu,@ev,@inner_right_sym}')
a('right',r'(v^{\prime}u^{\prime})(uv)=e',r'\rIE{@inner_right,@vpv,@right_assoc}')
a('inverse_exists',r'\exists w\in A\;((uv)w=e\land w(uv)=e)',r'\rEIStar{@inv,\rAI{@left,@right}}')
a('uv_unit',r'uv\in U(A,e)',r'\FormulaRefAuto{SemigroupUnitsAtIdentityDef}[def]{@sg,@e,@neutral,@uv,@inverse_exists}')
a('no_vw',r'uv\in U(A,e)',r'\rEE{@v_exists,@vw,@uv_unit}',('vw',))
a('no_uw',r'uv\in U(A,e)',r'\rEE{@u_exists,@uw,@no_vw}',('uw',))
a('closed',r'\forall u,v\in U(A,e)\;(uv\in U(A,e))',r'\rUI{\rRI{@u,\rUI{\rRI{@v,@no_uw}}}}',('u','v'))
a('unit_sg',r'\SemigroupAlg{U(A,e)}{\star}',r'\FormulaRefAuto{SemigroupClosedSubsetIsSemigroup}[thm]{@sg,@subset,@closed}')
a('result',r'U(A,e)\subseteq A\land\SemigroupAlg{U(A,e)}{\star}',r'\rAI{@subset,@unit_sg}')
path=Path('tex/B28-isomorphism-examples.tex');s=path.read_text(encoding='utf-8')
start=s.index('\n',s.index('[SemigroupUnitCarrierStructure]'))+1;end=s.index(r'\closeproofpartwideindR',start)
Path('tmp/metaproof-audit/b28-unit-body-before.tex').write_text(s[start:end],encoding='utf-8')
path.write_text(s[:start]+p.render()+s[end:],encoding='utf-8',newline='\n')
print('Unit carrier proof:',len(p.rows),'steps')
