from pathlib import Path
from named_proof import Proof
p=Proof();a=p.add
a('sg',r'\SemigroupAlg{A}{\star}',r'\rA')
a('e',r'e\in A',r'\rA')
a('idem',r'ee=e',r'\rA')
a('u',r'u\in eAe',r'\rA')
a('exists',r'\exists a\in A\;(u=(ea)e)',r'\FormulaRefAuto{SemigroupLocalCarrierDef}[def]{@sg,@e,@idem,@u}')
a('witness',r'a\in A\land u=(ea)e',r'\rA')
a('a',r'a\in A',r'\rAEa{@witness}')
a('value',r'u=(ea)e',r'\rAEb{@witness}')
a('ea',r'ea\in A',r'\FormulaRefAuto{SemigroupClosureAxiom}[ax]{@sg,@e,@a}')
a('eae',r'(ea)e\in A',r'\FormulaRefAuto{SemigroupClosureAxiom}[ax]{@sg,@ea,@e}')
a('value_sym',r'(ea)e=u',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@value}')
a('u_carrier',r'u\in A',r'\rIE{@value_sym,@eae}')
a('assoc_eea',r'(ee)a=e(ea)',r'\FormulaRefAuto{SemigroupAssociativityAxiom}[ax]{@sg,@e,@e,@a}')
a('assoc_eea_sym',r'e(ea)=(ee)a',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@assoc_eea}')
a('eea',r'e(ea)=ea',r'\rIE{@idem,@assoc_eea_sym}')
a('assoc_eeae',r'(e(ea))e=e((ea)e)',r'\FormulaRefAuto{SemigroupAssociativityAxiom}[ax]{@sg,@e,@ea,@e}')
a('assoc_eeae_sym',r'e((ea)e)=(e(ea))e',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@assoc_eeae}')
a('left',r'eu=u',r'\rIE{@value_sym,@eea,@value_sym,@assoc_eeae_sym}')
a('assoc_eaee',r'((ea)e)e=(ea)(ee)',r'\FormulaRefAuto{SemigroupAssociativityAxiom}[ax]{@sg,@ea,@e,@e}')
a('right',r'ue=u',r'\rIE{@value_sym,@idem,@value_sym,@assoc_eaee}')
a('properties_w',r'u\in A\land eu=u\land ue=u',r'\rAI{@u_carrier,\rAI{@left,@right}}')
a('properties',r'u\in A\land eu=u\land ue=u',r'\rEE{@exists,@witness,@properties_w}',('witness',))
a('all_properties',r'\forall u\in eAe\;(u\in A\land eu=u\land ue=u)',r'\rUI{\rRI{@u,@properties}}',('u',))
a('member',r'u\in A',r'\rAEa{@properties}')
a('all_members',r'\forall u\in eAe\;(u\in A)',r'\rUI{\rRI{@u,@member}}',('u',))
a('subset',r'eAe\subseteq A',r'\FormulaRefAuto{A\subseteq B\coloneq\forall x\,(x\in A\rightarrow x\in B)}[def]{@all_members}')
a('neutral_u',r'eu=u\land ue=u',r'\rAEb{@properties}')
a('neutral',r'\forall u\in eAe\;(eu=u\land ue=u)',r'\rUI{\rRI{@u,@neutral_u}}',('u',))
a('reflex',r'(ee)e=(ee)e',r'\rII')
a('e_value',r'e=(ee)e',r'\rIE{@idem,@idem,@reflex}')
a('e_exists',r'\exists a\in A\;(e=(ea)e)',r'\rEIStar{@e,@e_value}')
a('e_local',r'e\in eAe',r'\FormulaRefAuto{SemigroupLocalCarrierDef}[def]{@sg,@e,@idem,@e_exists}')
a('nonempty',r'eAe\neq\varnothing',r'\FormulaRefAuto{a\in A\vdash A\neq\varnothing}[thm]{@e_local}')
a('x',r'u\in eAe',r'\rA')
a('y',r'v\in eAe',r'\rA')
a('x_props',r'u\in A\land eu=u\land ue=u',r'\rRE{\rUE{@all_properties},@x}')
a('y_props',r'v\in A\land ev=v\land ve=v',r'\rRE{\rUE{@all_properties},@y}')
a('x_a',r'u\in A',r'\rAEa{@x_props}')
a('y_a',r'v\in A',r'\rAEa{@y_props}')
a('x_left',r'eu=u',r'\rAEa{\rAEb{@x_props}}')
a('y_right',r've=v',r'\rAEb{\rAEb{@y_props}}')
a('xy',r'uv\in A',r'\FormulaRefAuto{SemigroupClosureAxiom}[ax]{@sg,@x_a,@y_a}')
a('assoc_exy',r'(eu)v=e(uv)',r'\FormulaRefAuto{SemigroupAssociativityAxiom}[ax]{@sg,@e,@x_a,@y_a}')
a('assoc_exy_sym',r'e(uv)=(eu)v',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@assoc_exy}')
a('xy_left',r'e(uv)=uv',r'\rIE{@x_left,@assoc_exy_sym}')
a('xy_left_sym',r'uv=e(uv)',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@xy_left}')
a('assoc_xye',r'(uv)e=u(ve)',r'\FormulaRefAuto{SemigroupAssociativityAxiom}[ax]{@sg,@x_a,@y_a,@e}')
a('xy_right',r'(uv)e=uv',r'\rIE{@y_right,@assoc_xye}')
a('xy_fixed',r'(e(uv))e=uv',r'\rIE{@xy_left_sym,@xy_right}')
a('xy_value',r'uv=(e(uv))e',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@xy_fixed}')
a('xy_exists',r'\exists a\in A\;(uv=(ea)e)',r'\rEIStar{@xy,@xy_value}')
a('xy_local',r'uv\in eAe',r'\FormulaRefAuto{SemigroupLocalCarrierDef}[def]{@sg,@e,@idem,@xy_exists}')
a('closed',r'\forall u,v\in eAe\;(uv\in eAe)',r'\rUI{\rRI{@x,\rUI{\rRI{@y,@xy_local}}}}',('x','y'))
a('criteria',r'eAe\subseteq A\land eAe\neq\varnothing\land\forall u,v\in eAe\;(uv\in eAe)',r'\rAI{@subset,\rAI{@nonempty,@closed}}')
a('result',r'\mathsf{UHGr}(eAe;A,\star)',r'\FormulaRefAuto{SemigroupSubsemigroupCriterion}[thm]{@sg,@criteria}')
path=Path('tex/B28-isomorphism-examples.tex');s=path.read_text(encoding='utf-8')
start=s.index('\n',s.index('[SemigroupLocalCarrierStructure]'))+1;end=s.index(r'\closeproofpartwideindR',start)
Path('tmp/metaproof-audit/b28-local-body-before.tex').write_text(s[start:end],encoding='utf-8')
path.write_text(s[:start]+p.render()+s[end:],encoding='utf-8',newline='\n')
print('Local carrier proof:',len(p.rows),'steps')
