from pathlib import Path
from named_proof import Proof
p=Proof();a=p.add
a('iso',r'f:A\cong B',r'\rA')
a('e',r'e\in A',r'\rA')
a('neutral',r'\forall x\in A\;(ex=x\land xe=x)',r'\rA')
a('sg',r'\SemigroupAlg{A}{\star}',r'\FormulaRefAuto{SemigroupIsoSource}[thm]{@iso}')
a('tg',r'\SemigroupAlg{B}{\diamond}',r'\FormulaRefAuto{SemigroupIsoTarget}[thm]{@iso}')
a('f',r'f:A\to B',r'\FormulaRefAuto{SemigroupIsoFunction}[thm]{@iso}')
a('bij',r'f:A\bij B',r'\FormulaRefAuto{SemigroupIsoBijectiveAxiom}[ax]{@iso}')
a('hbij',r'h:B\bij A',r'\FormulaRefAuto{SemigroupIsoInverseCarrier}[thm]{@iso}')
a('h',r'h:B\to A',r'\FormulaRefAuto{Bijektive Funktion}[def]{@hbij}')
a('fe',r'f(e)\in B',r'\FormulaRefAuto{F\colon A\to B\dsep x\in A\vdash F(x)\in B}[thm]{@f,@e}')
a('neutral_iff',r'\begin{aligned}[t]&(\forall x\in A\;(ex=x\land xe=x))\\[-2pt]&\quad\leftrightarrow(\forall y\in B\;(f(e)y=y\land yf(e)=y))\end{aligned}',r'\FormulaRefAuto{SemigroupIsoIdentityZeroConditions}[thm]{@iso,@e}')
a('target_neutral',r'\forall y\in B\;(f(e)y=y\land yf(e)=y)',r'\rRE{\rLREa{@neutral_iff},@neutral}')
a('units',r'U(A,e)\subseteq A\land\SemigroupAlg{U(A,e)}{\star}',r'\FormulaRefAuto{SemigroupUnitCarrierStructure}[thm]{@sg,@e,@neutral}')
a('subset',r'U(A,e)\subseteq A',r'\rAEa{@units}')
a('unit_sg',r'\SemigroupAlg{U(A,e)}{\star}',r'\rAEb{@units}')
a('target_units',r'U(B,f(e))\subseteq B\land\SemigroupAlg{U(B,f(e))}{\diamond}',r'\FormulaRefAuto{SemigroupUnitCarrierStructure}[thm]{@tg,@fe,@target_neutral}')
a('target_subset',r'U(B,f(e))\subseteq B',r'\rAEa{@target_units}')
a('u',r'u\in A',r'\rA')
a('v',r'v\in A',r'\rA')
a('uv',r'uv\in A',r'\FormulaRefAuto{SemigroupClosureAxiom}[ax]{@sg,@u,@v}')
a('vu',r'vu\in A',r'\FormulaRefAuto{SemigroupClosureAxiom}[ax]{@sg,@v,@u}')
a('uv_op',r'f(uv)=f(u)f(v)',r'\FormulaRefAuto{SemigroupIsoOperation}[thm]{@iso,@u,@v}')
a('vu_op',r'f(vu)=f(v)f(u)',r'\FormulaRefAuto{SemigroupIsoOperation}[thm]{@iso,@v,@u}')
a('uv_reflect',r'uv=e\leftrightarrow f(uv)=f(e)',r'\FormulaRefAuto{SemigroupIsoEqualityReflection}[thm]{@iso,@uv,@e}')
a('vu_reflect',r'vu=e\leftrightarrow f(vu)=f(e)',r'\FormulaRefAuto{SemigroupIsoEqualityReflection}[thm]{@iso,@vu,@e}')
a('uv_iff',r'uv=e\leftrightarrow f(u)f(v)=f(e)',r'\rIE{@uv_op,@uv_reflect}')
a('vu_iff',r'vu=e\leftrightarrow f(v)f(u)=f(e)',r'\rIE{@vu_op,@vu_reflect}')
a('pair_reflex',r'(uv=e\land vu=e)\leftrightarrow(uv=e\land vu=e)',r'\FormulaRefAuto{P\leftrightarrow P}[thm]')
a('pair',r'(uv=e\land vu=e)\leftrightarrow(f(u)f(v)=f(e)\land f(v)f(u)=f(e))',r'\rLRS{@uv_iff,\rLRS{@vu_iff,@pair_reflex}}')
a('all_pair',r'\begin{aligned}[t]&\forall u,v\in A\;\bigl((uv=e\land vu=e)\\[-2pt]&\quad\leftrightarrow(f(u)f(v)=f(e)\land f(v)f(u)=f(e))\bigr)\end{aligned}',r'\rUI{\rRI{@u,\rUI{\rRI{@v,@pair}}}}',('u','v'))
a('x',r'u\in A',r'\rA')
a('fx',r'f(u)\in B',r'\FormulaRefAuto{F\colon A\to B\dsep x\in A\vdash F(x)\in B}[thm]{@f,@x}')
a('unit_x',r'u\in U(A,e)',r'\rA')
a('inverse_exists',r'\exists v\in A\;(uv=e\land vu=e)',r'\FormulaRefAuto{SemigroupUnitsAtIdentityDef}[def]{@sg,@e,@neutral,@unit_x}')
a('inverse_w',r'v\in A\land uv=e\land vu=e',r'\rA')
a('w_a',r'v\in A',r'\rAEa{@inverse_w}')
a('w_inverse',r'uv=e\land vu=e',r'\rAEb{@inverse_w}')
a('fw',r'f(v)\in B',r'\FormulaRefAuto{F\colon A\to B\dsep x\in A\vdash F(x)\in B}[thm]{@f,@w_a}')
a('xw_pair',r'(uv=e\land vu=e)\leftrightarrow(f(u)f(v)=f(e)\land f(v)f(u)=f(e))',r'\rRE{\rUE{\rRE{\rUE{@all_pair},@x}},@w_a}')
a('image_pair',r'f(u)f(v)=f(e)\land f(v)f(u)=f(e)',r'\rRE{\rLREa{@xw_pair},@w_inverse}')
a('image_inverse',r'\exists w\in B\;(f(u)w=f(e)\land wf(u)=f(e))',r'\rEIStar{@fw,@image_pair}')
a('image_unit_w',r'f(u)\in U(B,f(e))',r'\FormulaRefAuto{SemigroupUnitsAtIdentityDef}[def]{@tg,@fe,@target_neutral,@fx,@image_inverse}')
a('image_unit',r'f(u)\in U(B,f(e))',r'\rEE{@inverse_exists,@inverse_w,@image_unit_w}',('inverse_w',))
a('forward',r'u\in U(A,e)\rightarrow f(u)\in U(B,f(e))',r'\rRI{@unit_x,@image_unit}',('unit_x',))
a('unit_fx',r'f(u)\in U(B,f(e))',r'\rA')
a('target_inverse_exists',r'\exists w\in B\;(f(u)w=f(e)\land wf(u)=f(e))',r'\FormulaRefAuto{SemigroupUnitsAtIdentityDef}[def]{@tg,@fe,@target_neutral,@unit_fx}')
a('target_w',r'w\in B\land f(u)w=f(e)\land wf(u)=f(e)',r'\rA')
a('w_b',r'w\in B',r'\rAEa{@target_w}')
a('target_pair',r'f(u)w=f(e)\land wf(u)=f(e)',r'\rAEb{@target_w}')
a('hw',r'h(w)\in A',r'\FormulaRefAuto{F\colon A\to B\dsep x\in A\vdash F(x)\in B}[thm]{@h,@w_b}')
a('hw_value',r'f(h(w))=w',r'\FormulaRefAuto{F\colon A\bij B\dsep y\in B\vdash F(F^{-1}(y))=y}[thm]{@bij,@w_b}')
a('hw_value_sym',r'w=f(h(w))',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@hw_value}')
a('target_pair_hw',r'f(u)f(h(w))=f(e)\land f(h(w))f(u)=f(e)',r'\rIE{@hw_value_sym,@target_pair}')
a('hw_pair',r'\begin{aligned}[t]&(uh(w)=e\land h(w)u=e)\\[-2pt]&\quad\leftrightarrow(f(u)f(h(w))=f(e)\land f(h(w))f(u)=f(e))\end{aligned}',r'\rRE{\rUE{\rRE{\rUE{@all_pair},@x}},@hw}')
a('source_pair',r'uh(w)=e\land h(w)u=e',r'\rRE{\rLREb{@hw_pair},@target_pair_hw}')
a('source_inverse',r'\exists v\in A\;(uv=e\land vu=e)',r'\rEIStar{@hw,@source_pair}')
a('source_unit_w',r'u\in U(A,e)',r'\FormulaRefAuto{SemigroupUnitsAtIdentityDef}[def]{@sg,@e,@neutral,@x,@source_inverse}')
a('source_unit',r'u\in U(A,e)',r'\rEE{@target_inverse_exists,@target_w,@source_unit_w}',('target_w',))
a('backward',r'f(u)\in U(B,f(e))\rightarrow u\in U(A,e)',r'\rRI{@unit_fx,@source_unit}',('unit_fx',))
a('iff',r'u\in U(A,e)\leftrightarrow f(u)\in U(B,f(e))',r'\rLRI{@forward,@backward}')
a('all_iff',r'\forall u\in A\;(u\in U(A,e)\leftrightarrow f(u)\in U(B,f(e)))',r'\rUI{\rRI{@x,@iff}}',('x',))
a('image_y',r'y\in f[U(A,e)]',r'\rA')
a('image_exists',r'\exists u\in U(A,e)\;(y=f(u))',r'\FormulaRefAuto{C\subseteq A\dsep F\colon A\to B\dsep y\in F[C]\vdash\exists x\in C\,y=F(x)}[thm]{@subset,@f,@image_y}')
a('image_w',r'u\in U(A,e)\land y=f(u)',r'\rA')
a('image_w_unit',r'u\in U(A,e)',r'\rAEa{@image_w}')
a('image_w_value',r'y=f(u)',r'\rAEb{@image_w}')
a('image_w_value_sym',r'f(u)=y',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@image_w_value}')
a('image_w_a',r'u\in A',r'\FormulaRefAuto{A\subseteq B,\,x\in A\vdash x\in B}[thm]{@subset,@image_w_unit}')
a('image_w_iff',r'u\in U(A,e)\leftrightarrow f(u)\in U(B,f(e))',r'\rRE{\rUE{@all_iff},@image_w_a}')
a('image_w_target',r'f(u)\in U(B,f(e))',r'\rRE{\rLREa{@image_w_iff},@image_w_unit}')
a('target_y_w',r'y\in U(B,f(e))',r'\rIE{@image_w_value_sym,@image_w_target}')
a('target_y',r'y\in U(B,f(e))',r'\rEE{@image_exists,@image_w,@target_y_w}',('image_w',))
a('image_forward',r'y\in f[U(A,e)]\rightarrow y\in U(B,f(e))',r'\rRI{@image_y,@target_y}',('image_y',))
a('target_assume',r'y\in U(B,f(e))',r'\rA')
a('y_b',r'y\in B',r'\FormulaRefAuto{A\subseteq B,\,x\in A\vdash x\in B}[thm]{@target_subset,@target_assume}')
a('hy',r'h(y)\in A',r'\FormulaRefAuto{F\colon A\to B\dsep x\in A\vdash F(x)\in B}[thm]{@h,@y_b}')
a('hy_value',r'f(h(y))=y',r'\FormulaRefAuto{F\colon A\bij B\dsep y\in B\vdash F(F^{-1}(y))=y}[thm]{@bij,@y_b}')
a('hy_value_sym',r'y=f(h(y))',r'\FormulaRefAuto{a=b\vdash b=a}[thm]{@hy_value}')
a('hy_target',r'f(h(y))\in U(B,f(e))',r'\rIE{@hy_value_sym,@target_assume}')
a('hy_iff',r'h(y)\in U(A,e)\leftrightarrow f(h(y))\in U(B,f(e))',r'\rRE{\rUE{@all_iff},@hy}')
a('hy_unit',r'h(y)\in U(A,e)',r'\rRE{\rLREb{@hy_iff},@hy_target}')
a('hy_image',r'f(h(y))\in f[U(A,e)]',r'\FormulaRefAuto{C\subseteq A\dsep F\colon A\to B\dsep x\in C\vdash F(x)\in F[C]}[thm]{@subset,@f,@hy_unit}')
a('y_image',r'y\in f[U(A,e)]',r'\rIE{@hy_value,@hy_image}')
a('image_backward',r'y\in U(B,f(e))\rightarrow y\in f[U(A,e)]',r'\rRI{@target_assume,@y_image}',('target_assume',))
a('image_iff',r'y\in f[U(A,e)]\leftrightarrow y\in U(B,f(e))',r'\rLRI{@image_forward,@image_backward}')
a('all_image_iff',r'\forall y\;(y\in f[U(A,e)]\leftrightarrow y\in U(B,f(e)))',r'\rUI{@image_iff}')
a('image_eq',r'f[U(A,e)]=U(B,f(e))',r'\FormulaRefAuto{\forall x\,(x\in A\leftrightarrow x\in B)\vdash A=B}[ax]{@all_image_iff}')
a('restriction',r'f|_{U(A,e)}:U(A,e)\cong f[U(A,e)]',r'\FormulaRefAuto{SemigroupIsoClosedCarrierRestriction}[thm]{@iso,@subset,@unit_sg}')
a('result',r'f|_{U(A,e)}:U(A,e)\cong U(B,f(e))',r'\rIE{@image_eq,@restriction}')
path=Path('tex/B28-isomorphism-examples.tex');s=path.read_text(encoding='utf-8')
start=s.index('\n',s.index(r'\proofpartwide{Abschluss und Transport der Einheiten}'))+1;end=s.index(r'\closeproofpartwide',start)
Path('tmp/metaproof-audit/b28-unittransport-body-before.tex').write_text(s[start:end],encoding='utf-8')
path.write_text(s[:start]+p.render()+s[end:],encoding='utf-8',newline='\n')
print('Unit transport:',len(p.rows),'steps')
