"""Prepare and audit the integer construction companions and the B17 interface.

The migration manifest preserves the original formulas and public destinations.
Proof-table bodies are checked against that baseline plus the three documented
corrections of 2026-09-21. These checks establish document integrity, not formal
verification of mathematical inference rules.
"""
from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re
import runpy

ROOT = Path(__file__).resolve().parents[1]
DIRECTORY = ROOT / "registry/integers"
MANIFEST = json.loads((ROOT / "scripts/integers-manifest.json").read_text(encoding="utf-8"))
CORRECTIONS = json.loads((ROOT / "scripts/integers-proof-corrections-2026-09-21.json").read_text(encoding="utf-8"))["proofs"]
HELPERS = runpy.run_path(str(ROOT / "scripts/differences-editions.py"))
registry = HELPERS["registry"]
row_label = HELPERS["row_label"]
id_map = HELPERS["id_map"]
aux_labels = HELPERS["aux_labels"]
records_equal = HELPERS["records_equal"]
PUBLIC_IDS = set(id_map(MANIFEST["public_records"]))
PRIVATE_IDS = set(id_map(MANIFEST["private_records"]))


def moved_record(row):
    row = list(row)
    if row[0] == "ID":
        row[3] = row[3].replace(":17.", ":17E.")
    else:
        row[1] = row[1].replace(":17.", ":17E.")
        row[3] = row[3].replace("17.", "17E.", 1)
    return row


EXPECTED_PROOF = [moved_record(row) for row in MANIFEST["private_records"]]


def main_records():
    base = ROOT / "registry/_B17"
    rows = registry(base.with_suffix(".registry.tsv"))
    records_equal(rows, MANIFEST["public_records"], "B17")
    if set(id_map(rows)) != PUBLIC_IDS:
        raise ValueError("B17: public statement ownership differs")
    aux = aux_labels(base.with_suffix(".aux"))
    for label, expected in MANIFEST["public_aux"].items():
        if aux.get(label) != tuple(expected):
            raise ValueError(f"B17: public number/target changed: {label}, {aux.get(label)}, expected {expected}")
    if {row_label(row) for row in MANIFEST["private_records"]} & set(aux):
        raise ValueError("B17 still declares extracted private labels")
    return rows, aux


def proof_records():
    base = DIRECTORY / "_B17-integers-proofs"
    rows = registry(base.with_suffix(".registry.tsv"))
    records_equal(rows, EXPECTED_PROOF, "integer proofs")
    if set(id_map(rows)) != PRIVATE_IDS:
        raise ValueError("Proof volume: missing private IDs or duplicate public ownership")
    aux = aux_labels(base.with_suffix(".aux"))
    for row in rows:
        label = row_label(row)
        if label not in aux or not aux[label][0].startswith("17E."):
            raise ValueError(f"Proof volume: missing companion number: {label}")
        if row[0] != "ID" and row[3] != aux[label][0]:
            raise ValueError(f"Proof volume: registry/AUX mismatch: {label}")
    if {row_label(row) for row in MANIFEST["public_records"]} & set(aux):
        raise ValueError("Proof volume must import public B17 labels, not write them locally")
    return rows, aux


def write_import(name, rows, aux_path):
    labels = {row_label(row) for row in rows}
    (DIRECTORY / (name + ".registry.tsv")).write_text(
        "".join("\t".join(row) + "\n" for row in rows), encoding="utf-8")
    lines = []
    for line in aux_path.read_text(encoding="utf-8-sig").splitlines():
        match = re.match(r"\\newlabel\{([^}]+)\}", line)
        if match and match[1] in labels:
            lines.append(line)
    target = DIRECTORY / (name + ".aux")
    target.write_text("\\relax\n" + "\n".join(lines) + "\n", encoding="utf-8")
    if set(aux_labels(target)) != labels:
        raise ValueError(f"{name}: incomplete filtered AUX import")


def prepare():
    DIRECTORY.mkdir(parents=True, exist_ok=True)
    rows, _ = main_records()
    write_import("b17-external", rows, ROOT / "registry/_B17.aux")
    (DIRECTORY / "position.tex").write_text(
        "% Independent construction numbering; generated by integers-editions.py.\n"
        "\\renewcommand{\\FormulaBandID}{17E}\n"
        "\\setcounter{file}{17}\n"
        "\\setcounter{chapter}{1}\n"
        "\\setcounter{section}{0}\n"
        "\\setcounter{subsection}{0}\n"
        "\\setcounter{formulaDef}{0}\n"
        "\\setcounter{formulaThm}{0}\n"
        "\\setcounter{formulaAx}{0}\n", encoding="utf-8")
    print("Integers: 85 public B17 identities imported; private construction uses prefix 17E.")


def prepare_reading():
    main_records()
    rows, _ = proof_records()
    write_import("proofs-reading", rows, DIRECTORY / "_B17-integers-proofs.aux")
    print("Integers: reading imports prepared from 137 private identities.")


def audit_sources():
    main = (ROOT / "Bd. 17 - Ganze Zahlen.tex").read_text(encoding="utf-8-sig")
    if re.search(r"\\begin\{tabproof", main):
        raise ValueError("B17 still contains a formal proof table")
    text = (ROOT / "tex/b17/integers/construction.tex").read_text(encoding="utf-8-sig")
    tables = list(re.finditer(r"\\begin\{(tabproof\w*)\}.*?\\end\{\1\}", text, re.S))
    actual = {}
    for match in tables:
        anchors = re.findall(r"\\hypertarget\{integers.proof.([^}]+)\}\{\}", text[:match.start()])
        if not anchors or anchors[-1] in actual:
            raise ValueError("Missing/duplicate proof identity")
        body = re.sub(r"\\hypertarget\{integers.statement.[^}]+\}\{\}", "", match[0])
        actual[anchors[-1]] = hashlib.sha256(re.sub(r"\s+", "", body).encode()).hexdigest()
    expected = dict(MANIFEST["proofs"])
    for key, correction in CORRECTIONS.items():
        if expected.get(key) != correction["original"]:
            raise ValueError(f"Correction baseline does not match the migration manifest: {key}")
        expected[key] = correction["corrected"]
    if actual != expected:
        changed = sorted(key for key in actual.keys() | expected.keys()
                         if actual.get(key) != expected.get(key))
        raise ValueError(f"Proof tables differ from the checked baseline and corrections: {changed}")
    print("Source migration: 94 proof tables; 91 unchanged and 3 documented corrections; no proof table remains in B17.")


def audit(*, check_group_navigation=True):
    from pypdf import PdfReader

    audit_sources()
    public, public_aux = main_records()
    proofs, proof_aux = proof_records()
    for name, rows, aux in (("b17-external", public, public_aux), ("proofs-reading", proofs, proof_aux)):
        records_equal(registry(DIRECTORY / (name + ".registry.tsv")), rows, name)
        if aux_labels(DIRECTORY / (name + ".aux")) != {row_label(row): aux[row_label(row)] for row in rows}:
            raise ValueError(f"{name}: stale import")
    publisher = runpy.run_path(str(ROOT / "scripts/publish-pdfs.py"))
    cache = {}

    def links(pdf, reader):
        result = set()
        for action in publisher["remote_actions"](reader):
            target = (pdf.parent / publisher["file_name"](action)).resolve()
            if not target.is_relative_to(ROOT) or not target.is_file():
                raise ValueError(f"{pdf.name}: missing/outside PDF target: {target}")
            if target not in cache:
                cache[target] = set(PdfReader(target).named_destinations)
            destination = str(action.get("/D"))
            if destination not in cache[target]:
                raise ValueError(f"{pdf.name}: missing destination {destination} in {target}")
            result.add((target, destination))
        return result

    main_pdf = ROOT / "registry/_B17.pdf"
    group_pdf = ROOT / "registry/differences/_B41-differences-reading.pdf"
    for edition in ("proofs", "reading"):
        base = DIRECTORY / f"_B17-integers-{edition}"
        records_equal(registry(base.with_suffix(".registry.tsv")), proofs if edition == "proofs" else [], edition)
        pdf = base.with_suffix(".pdf")
        reader = PdfReader(pdf)
        publisher["assert_build_ready"](pdf, reader)
        publisher["audit_local_targets"](reader, pdf)
        expected = {f"integers.{edition}"}
        if edition == "proofs":
            expected.update("integers.proof." + key for key in MANIFEST["proofs"])
            expected.update("integers.statement." + key for key in PRIVATE_IDS)
        if missing := expected - set(reader.named_destinations):
            raise ValueError(f"{edition}: missing targets: {missing}")
        actual_links = links(pdf, reader)
        companion = "reading" if edition == "proofs" else "proofs"
        expected_links = {
            ((DIRECTORY / f"_B17-integers-{companion}.pdf").resolve(), f"integers.{companion}"),
            (group_pdf.resolve(), "differences.reading"),
        }
        if edition == "proofs": expected_links.add((main_pdf.resolve(), "integers.main"))
        if missing := expected_links - actual_links:
            raise ValueError(f"{edition}: missing navigation: {missing}")
        print(f"Integers {edition}: {len(reader.pages)} pages; identities, statements and links passed.")
    reader = PdfReader(main_pdf)
    actual_links = links(main_pdf, reader)
    expected_links = {
        ((DIRECTORY / "_B17-integers-reading.pdf").resolve(), "integers.reading"),
        ((DIRECTORY / "_B17-integers-proofs.pdf").resolve(), "integers.proofs"),
    }
    if expected_links - actual_links:
        raise ValueError("B17: missing companion navigation")
    if any(target not in reader.named_destinations for _, target in public_aux.values()):
        raise ValueError("B17: missing public PDF target")
    publisher["assert_build_ready"](main_pdf, reader)
    publisher["audit_local_targets"](reader, main_pdf)
    print("B17: all 85 public identities, original numbers and destinations preserved.")
    if check_group_navigation:
        group_links = links(group_pdf, PdfReader(group_pdf))
        if missing := expected_links - group_links:
            raise ValueError(f"B41 reading: missing return navigation to integer companions: {missing}")
        print("B41 reading: return links to both integer companions passed.")
    else:
        print("B41 return-navigation check deferred until its companion build.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("prepare", "prepare-reading", "audit", "audit-sources"))
    parser.add_argument("--skip-group-navigation", action="store_true",
                        help="For staged audit runs before B41 is rebuilt; still check all B17 outgoing links.")
    args = parser.parse_args()
    if args.skip_group_navigation and args.mode != "audit":
        parser.error("--skip-group-navigation is only valid with audit")
    {"prepare": prepare, "prepare-reading": prepare_reading,
     "audit": lambda: audit(check_group_navigation=not args.skip_group_navigation),
     "audit-sources": audit_sources}[args.mode]()
